- package-lock.json
- package.json
- src/decorator.spec.ts
- src/decorator.ts
I ran into issues using this package as I'm using fastify which doesn't have the same request methods as express.
So I've created this PR. However I'm a little unsure if I went the right way with checking the request type. I looked for the `originalUrl` property which is only on Express.
I'm not happy with that solution but as there is no way to check something is an instance of an interface I'm not sure what else I can do. Any Suggestions for a better solution would be great.
> feat: added support for Fastify requests

- src/paginate.spec.ts
- src/paginate.ts
First step was to split out some parts of larger paginate function into smaller functions and added tests.
Two of the tests contain filter values that have a `:` and they currently fail. Need to make those tests work.
> Better splitting of the filter string to allow for filter values that contain a colon

- src/paginate.ts
As previously described in https://github.com/ppetzold/nestjs-paginate/issues/96, there is an non-intuitive behavior of `andWhere` method in TypeORM's QueryBuilder, resulting in mixing of different search/filter options for this library. The issue seems to be again primarily related to Postgres, as discussed before in https://github.com/ppetzold/nestjs-paginate/pull/97.
Following the example from https://github.com/ppetzold/nestjs-paginate/issues/96...
The library implementation in `SomeService`:
```
paginate(query, this.someRepository, {
...,
searchableColumns: [<property1>, <property2>],
filterableColumns: {
<property3>: [FilterOperator.EQ, FilterOperator.IN]
}
}
```
and the following request:
```
path/to/endpoint?search=<value1>&filter.<property3>=$in:<value2>,<value3>
```
will return …
> fix: isolate all where clauses

- README.md
- src/paginate.spec.ts
- src/paginate.ts
Were added support for between operator that was mentioned in the [#77](https://github.com/ppetzold/nestjs-paginate/issues/77) issue.
Were used similar approach as with `$in` operator where we pass arguments separating them by a comma.
So operator `btw`(between) takes two arguments separated by a comma and can be used in the next way: `filter.age=$btw:4,6`
> Support of betweet operator

- src/paginate.ts
Between operator didn't work properly, were missed splitting of arguments
> fix: add splitting of values for btw operator

- src/paginate.spec.ts
- src/paginate.ts
A query resulting in zero records should not, in my opinion, generate the `last` link. Currently, `last` link with `page=0` is returned.
Optionally, this could be also modified for _"faulty"_ queries, such as querying page 2, when there were already no records found on the first page.
> fix: return only current link for zero results

- package-lock.json
- package.json
- src/paginate.ts
Closes #239 
This PR bumps typeorm to version 0.3.x which includes breaking changes.
In order for developers to understand nestjs-paginate version should also be brought up to 0.3.x i guess.
Tests where running through.
Happy to accept any feedback!
BR Jakob
> bumps typeorm to 0.3.6 - BREAKING CHANGE

- README.md
- src/paginate.spec.ts
- src/paginate.ts
Closes #267.
I believe this is the official "typeorm" way of doing it (typeorm/typeorm#685). I think it doesn't work on all databases but that's for the typeorm project to worry about.
```ts
query.addOrderBy('record.field', 'ASC', 'NULLS LAST');
```
I added a new test closure for the new functionality, LMK if maybe there should be more, I also updated the readme.
> Ability to specify whether null records should be first or last when sorting.

- README.md
- src/paginate.spec.ts
- src/paginate.ts
* Add config parameter to generate relative paths in links, as requested in #214.
* Add config parameter to override origin from query parameters. Useful when running behind a proxy accepting requests at a different url.
__Previous behavior__
Append `?page=...` to `path` from `PaginateQuery` passed to `paginate()` function. `path` can be either a relative or an absolute path.
__New default behavior__
Same as previous behavior.
__Relative paths__
Set `relativePaths = true` in config passed to `paginate()` function. Generated link will no longer include the origin part of the url.
__Override orgin__
Set `origin` to the origin to use instead of the one in the `path` property in the query parameters. I.e. if `origin = 'https://cats.example'`, a request sent to `http://localhost/cats` will get …
> Customized links

- src/__tests__/cat-toy.entity.ts
- src/__tests__/cat.entity.ts
- src/__tests__/size.embed.ts
- src/paginate.spec.ts
- src/paginate.ts
This PR fixes issues when using embedded entities. Trying to filter, sort or search an embedded entity would previously generate an exception due to incorrectly generated sql aliases.
> Embedded entities

- README.md
- src/paginate.spec.ts
- src/paginate.ts
Related to https://github.com/ppetzold/nestjs-paginate/issues/194
This PR aims to include the `$ilike` operator.
The main idea is to allow the ilike operator to any filter needed without using the _searchable_ column. 
Added a new unit test for the ilike scenario: `should return result based on $ilike filter`
**Future work:** I am planning to create a new contribution to allow using `$ilike` operator with multiple options. (i.e: `$ilike:Active Und, Declined due, Any type of`).
> Added $ilike operator

- .gitignore
- README.md
- src/helper.ts
- src/paginate.spec.ts
- src/paginate.ts
fix https://github.com/ppetzold/nestjs-paginate/issues/393
> feat: allow unpaginated request

- src/paginate.ts
Hey !
As discussed in #436 here is my try to fix the following issues: 
#436, #435, #366
The PR is split into two commits.
The tests are running through, but of course the tests are only for sqlite & so the coverage for postgres/coachrochdb is not given....
BR Jakob
> fix: update searchBy query to allow searchBy on other column types than text

- src/paginate.spec.ts
- src/paginate.ts
This should fix #460, introduced by #442
> fix: bind ilike/like parameters to prevent sql injection

- README.md
- src/paginate.spec.ts
- src/paginate.ts
The `$ilike` operator as its currently implemented, introduces a wildcard automatically for the caller. The net effect is that the query cannot use indices.
This PR introduces a new "starts with" operator `$sw` which as the name implies provides the ability to search by prefix. This *can* make use of indices.
> feat: introduce starts with ($sw) operator

- README.md
- src/__tests__/cat.entity.ts
- src/paginate.spec.ts
- src/paginate.ts
As an developer, i want to fetch eager relationships automatically when querying using repos, so the `nestjs-paginate` behavior will get similar to typeorm default behavior
Sometimes we need to get nested relationships for nested entities, so, create a strategy to handle eager loads can help developers to increase their productivity
- create the configuration field `loadEagerRelations` as opitional
- when set `loadEagerRelations` auto load all eager relations and nested eager relations
- implement the tests suites
> feat: implement auto EagerLoads in library

- README.md
- src/paginate.ts
Leave the user the choice to choose between limit/offset and take/skip.
By doing so this avoid user to create a custom queryBuilder to pass to `paginate` function.
> Related to issue: https://github.com/typeorm/typeorm/issues/5670
> Allow user to choose between limit/offset and take/skip.

- package.json
With `"prepare": "tsc"` (or `"prepare": "npm run build"`) we can use `npm install` directly on a fork.
> Added prepare script for installation from repo

- README.md
- src/filter.ts
Closes #534
This PR adds the contains operator to the list of operators. This corresponds to `ArrayIncludes`.
Perhaps the name `contains` is incorrect? maybe `includes` or something similar would be better. Open to feedback.
> feat: contains operator

- src/helper.ts
This commit updates the Column type to properly infer the relation properties of entities that use lazy loading, instead of inferring the properties of a Promise. This resolves an issue where the Column type would throw type errors when trying to access properties of the relation.
Fixes #582
> fix(types/Column): infer lazy-loaded relations

- src/paginate.ts
[ServiceUnavailableException](https://github.com/nestjs/nest/blob/master/packages/common/exceptions/service-unavailable.exception.ts) has an argument to add a message
> refactor: add message to named exception

- src/paginate.ts
Ran into the issue where I have the following entities relations structure:
```
paymentBatch
|____payments
|____approvals
|____user
```
Which resulted in the following error:
```
'TypeORMError: "payments_approvals" alias was not found. Maybe you forgot to join it?\n'
```
While debugging, I noticed that on calling `createQueryBuilderRelations` for `user` table, `prefix` param passed is `payments_approvals`, while for a proper join, it should have used `alias` instead with `__root_payments_approvals`
On calling `createQueryBuilderRelations` recursively alias param should be build from alias of parent relation first, and if it doesn't exist (first iteration) take prefix.
P.S. sorry if my PR is not too formalized, but I didn't find any template. Please let me know if I should fix it anyhow.
> fix: on nested relations discovery use alias of parent relation first

- src/helper.ts
- src/paginate.spec.ts
- src/paginate.ts
This PR attempts to address #518 by introducing a `_rel` suffix to all relationship aliases so that `parent.relationship.id` doesn't conflict with `parent.relationship_id` (a common occurence with TypeORM's default naming strategy).
I do not have enough understanding of the entire codebase to be confident that this is the optimal solution, but it shows a solution, which you should feel free to improve upon. I drafted this against the test suite, which are all passing, except for 1. Appearantly my solution makes it so that a virtual column filter is now selected in the resulting items, which was not the case before, this should be fixed but I don't know where this happens.
Also, the test suite should be extended to cover MySQL, if you draft up how you would like to extend the current …
> Add `_rel` suffix to relationship columns to avoid duplicate columns

- src/paginate.spec.ts
- src/paginate.ts
The `PaginateConfig.relations` field can now be given as `string[]` too:
```
{
relations: ["cat", "cat.home", "cat.home.pillow"]
}
```
should I mention it in the docs anywhere, or shall we take satisfaction knowing that people won't bump into #738 anymore? :)
closes #738
> feat: Support dot notation syntax for nested relations

- src/__tests__/cat-toy.entity.ts
- src/__tests__/toy-shop-address.entity.ts
- src/__tests__/toy-shop.entity.ts
- src/helper.ts
- src/paginate.spec.ts
- src/paginate.ts
It wasn't easy, or at least I didn't find an easy way, I found one internal method in Typeorm repos, that does the transform, the main problem was with aliases, we are using a custom mechanism for it here, not sure is it right or no, but changing it will be a bigger hassle than remap Typeform ones 
fix for this one https://github.com/ppetzold/nestjs-paginate/issues/750
and I saw another similar issue
> fix: implemented a proper mechanism for using where condition in options

- .gitignore
- src/filter.ts
- src/paginate.spec.ts
This will group the the $or filters first then the rest of the where cause will be built.
This fixes #595
> fix: or filters are grouped together

- src/swagger/api-paginated-query.decorator.ts
- src/swagger/pagination-docs.spec.ts
This includes `sortableColumns` from `paginationConfig` in swagger config. It's useful for generating sortable columns in frontend.
> feat: Add `sortBy` columns to swagger

- src/swagger/api-paginated-query.decorator.ts
- src/swagger/pagination-docs.spec.ts
As I understand - searchBy field should be an array.
> Updated searchBy definition to array instead of string 

- src/paginate.ts
When query select pass column without primary key in response all columns including relations columns shows those not including in config.select.
Issue is fixed will small check if query.select doesn't includes primary key user config.select as columns.
> fix: select security bug

- README.md
- package-lock.json
- package.json
- src/decorator.spec.ts
- src/decorator.ts
- src/paginate.spec.ts
- src/paginate.ts
- src/swagger/api-paginated-query.decorator.ts
- src/swagger/paginated-swagger.type.ts
- src/swagger/pagination-docs.spec.ts
Re-re-submit of #769 
---
This changeset implements the following syntactic changes:
* Change `page` to `page[number]`
* Change `limit` to `page[size]`
* Change `sortBy` to `sort`
* Change current syntax (`field:ASC/DESC`) to a comma separated ordered list of the sort fields with minus as desc operator (`field1,-field2`)
* Change `filter.field` to `filter[field]`
*  Change `search` to `@search[query]`
* Change `searchBy` to `@search[fields]`
* Allow `@search` as a shorthand for `@search[query]` (without the possibility to then specify fields)
The changeset tries to converge as soon as possible, so even though the syntax changed, none of these changes alters the produced `PaginateQuery`, or any code outside `decorator.ts`
---
It also refactored the parsing logic and the decorator tests. …
> JSON:API compliant query parameters

- src/helper.ts
- src/paginate.ts
* Fixed a problem where enums would litter the autocompletion with the keys of the String prototype.
* Added dev comments to `Column`'s ternary of doom
* Fixes #866 (I think, can't check in my IDE)
> Improved `PaginateConfig` and `Column` autocompletion

- src/paginate.spec.ts
- src/paginate.ts
As suggested in #958 I've created a failing test case to show case the bug identified with that issue.
BR Jakob
> #958 - adds a failing test case for "query limit should be used even if maxLimit = NO_PAGINATION"

- src/decorator.spec.ts
- src/decorator.ts
- src/paginate.ts
Currently, when the `@Paginate()` decorator is used alongside the `@MessagePattern()` decorator within a NestJS microservice, an error is thrown. This occurs because `ExecutionContextHost.switchToHttp().getRequest()` does not contain a `query` key in 'rpc' mode, leading to `undefined` being returned and causing the following `TypeError`:
```
TypeError: Cannot read properties of undefined (reading 'searchBy')
```
This error specifically arises due to the incompatibility of the `@Paginate()` decorator expecting HTTP request objects in an environment where such objects are not available.
> Fix TypeError When Using @Paginate() with @MessagePattern() (@nestjs/microservices)

- src/filter.ts
- src/paginate.spec.ts
There was a bug regarding multifilter.
The filters were split depending on whether they had an or operator or an and operator somewhere. However, multifilter may start with an and operator and have or operators inside. This meant that they were used twice and it also caused problems that an and operator binds stronger than an or operator.
Example: 
```node
filter: {
name: ['Milo', '$or:Garfield'],
color: ['brown', '$or:white'],
}
```
SQL Query: `... WHERE ( ("__root"."name" = "Milo" OR "__root"."name" = "Garfield" AND "__root"."color" = "brown" OR "__root"."color" = "white") AND ("__root"."name" = "Milo" OR "__root"."name" = "Garfield" AND "__root"."color" = "brown"  OR "__root"."color" = "white")`
(See: `... OR "__root"."name" = "Garfield" AND "__root"."color" = "brown" OR ...`)
Now in …
> Fix sql query for multifilter

- src/filter.ts
- src/paginate.spec.ts
I want use filter `contains` at array column(postgres)
but error occured
```
QueryFailedError: operator does not exist: integer @> unknown
at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at SelectQueryBuilder.loadRawResults (/app/src/query-builder/SelectQueryBuilder.ts:3555:25)
at SelectQueryBuilder.executeEntitiesAndRawResults (/app/src/query-builder/SelectQueryBuilder.ts:3320:26)
at SelectQueryBuilder.getManyAndCount (/app/src/query-builder/SelectQueryBuilder.ts:1756:36)
at paginate (/app/node_modules/nestjs-paginate/src/paginate.ts:353:32)
at ManagerUserService.findAll (/app/src/manager/admin/user/manager-user.service.ts:62:20)
at …
```
> Fix array contains fail when postgres because add cardinality

- README.md
- src/paginate.ts
This PR introduces an enhancement to the search functionality in the paginate function, allowing for more flexible and powerful searches across multiple columns.
- Modified the search logic in the paginate function to split the search query into individual words.
- Implemented a nested Brackets structure to apply each word across all searchable columns.
- Used AND conditions between different words and OR conditions between columns for each word.
- Maintained type casting for PostgreSQL and CockroachDB to ensure compatibility.
This change addresses a user-reported limitation where searching for multiple words or IDs in the same query was not possible. The new implementation allows for more natural search queries that can include multiple words and numeric IDs, searching across all …
> Enhanced Multi-Word Search Functionality

- package-lock.json
- package.json
- src/decorator.spec.ts
- src/swagger/pagination-docs.spec.ts
Upgraded nestjs to v11 for test
Breaking Change:
- None (No main code change from @nestjs/swagger@11.0.2)
Needed to changed test du to CustomParamFactory type change See: https://github.com/nestjs/nest/commit/e9d57dd795598e3d42e0d153031a203a372795aa
Do you prefer I use type assertion or method implementation that throws error ?
I don't know if it's possible to create test with both of the dependancy but it may be useless has @nestjs/swagger@11 doesn't have any breaking change from @nestjs/swagger@8
> Add Compatibility With NestJs V11

- .gitignore
- README.md
- package-lock.json
- package.json
- src/__tests__/cat-hair.entity.ts
- src/__tests__/cat-home-pillow.entity.ts
- src/__tests__/cat-home.entity.ts
- src/__tests__/cat-toy.entity.ts
- src/__tests__/cat.entity.ts
- src/__tests__/column-option.ts
- src/__tests__/toy-shop-address.entity.ts
- src/__tests__/toy-shop.entity.ts
- src/decorator.spec.ts
- src/decorator.ts
- src/filter.ts
- src/helper.ts
- src/paginate.spec.ts
- src/paginate.ts
This pull request enhances the cursor-based pagination support in `nestjs-paginate`, building upon the initial implementation from #1049-#1050, and introduces a new `weightChange` decimal column to the `CatEntity` along with supporting changes for date column management. The updated pagination implementation introduces a robust and flexible cursor generation mechanism, supporting multiple column types (e.g., dates, numbers, decimals) and improving database compatibility across MySQL, PostgreSQL, and SQLite.
1. **Enhanced Cursor Generation**:
- Introduced a new cursor generation system that transforms column values into a composite string (e.g., `V001671444000000` for dates, `Y00000000001V2500` for numbers/decimals), supporting multiple sortable columns (e.g., …
> feat: improve cursor pagination

- README.md
- src/helper.ts
- src/paginate.spec.ts
- src/paginate.ts
https://github.com/ppetzold/nestjs-paginate/issues/960
if not contain primary key, add selection automatically.
> feat: add auto pk selection

- README.md
- src/paginate.spec.ts
- src/paginate.ts
1. **Improved `generateCursor` Function**
- **Problem**: The original `generateCursor` function did not handle relation columns or embedded fields (e.g., `toys.(size.height)`). It assumed direct property access (`item[column]`), which failed for nested structures and arrays.
- **Solution**: Rewrote `generateCursor` to dynamically traverse nested property paths, including relation arrays (e.g., `toys`), and compute min/max values based on sort direction and link type (`previous` or `next`).
- **Details**:
- Added support for nested property paths using `propertyPath` and `propertyName.split('.')`.
- For arrays (e.g., `toys`), it calculates the minimum value for `ASC`/`previous` and maximum value for `DESC`/`next` (using XOR logic: `(direction === 'ASC') !== (linkType === 'previous')`).
2. …
> Enhance Cursor Pagination for Relation and Embedded Columns

- README.md
- src/paginate.spec.ts
- src/paginate.ts
related issue: resolves #950 
This PR introduces wildcard support in select parameters, allowing users to select all columns from main and relation entities using '*' notation. This enhancement provides more flexibility in column selection and simplifies queries when working with related entities.
- Added support for '*' wildcard to select all columns from main entity
- Added support for 'relation.*' wildcard to select all columns from relation entities
- Implemented wildcard expansion for both config.select and query.select
- Added handling for embedded entity columns in wildcard expansion
1. Wildcard Expansion:
- Main entity: '*' expands to all columns of the main entity (including embedded entity)
- Relation entities: 'relation.*' expands to all columns of the specified relation
- …
> feat: add wildcard support for select parameters
